name: "application-example"
tenant: "example-company"

containers:
  default:
    name: "ghcr.io/ertia-io/images/application-example"
    containerFile: "../Dockerfile"
    buildContext: "../."
    pullSecretName: "apps-registry-credential"

flux:
  name: "ghcr.io/ertia-io/flux/application-example"
  pullSecretName: "apps-registry-credential"

helm:
  name: "ghcr.io/ertia-io/charts/application-example"
  chartPath: "./helm/application-example"
  valuesFile: "./helm/application-example/values.yaml"
  pullSecretName: "apps-registry-credential"
  image:
    repositoryPath: "image.repository"
    tagPath: "image.tag"
    pullSecretsPath: "imagePullSecrets"
  environments:
    test:
      valuesFile: "./values-test.yaml"
